language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
  - "lts/*"
  - "4.0"
  - "0.12"
  - "0.10"

# The following are currently not supported:
#  - "0.8"
#  - "0.6"

notifications:
  email: false
before_install:
  - npm install -g npm@latest
  - npm i
before_script:
  - npm prune
script:
  - npm test
